### ISSUE TITLE
Vajíčkový festival

### ISSUE THREAD

**Issue by OtiCzech** [Tsbook/StardewValleyCZE#1]
Ahoj po uplnutí eventu nastane black screen..

**Comment by MlokoLubo** [comment]
Ahoj, taky se mi to stalo + při eventu byl text v angličtině a potom v češtině, to samé Linus event (večer jak vybírá odpadky) text byl v anglině i češtině

**Comment by Term1us** [comment]
Zdravím mám ten stejný problém a navíc při eventu se Abigail ani nehne a stejně vyhraje 😄

**Comment by Tsbook** [comment]
Opraveno ve verzi 0.2.1. Teď by už festival měl doběhnout do konce a v pořádku hráče navrátit do hry.
