### ISSUE TITLE
pár_malých_chyb

### ISSUE THREAD

**Issue by MlokoLubo** [Tsbook/StardewValleyCZE#2]
Ahoj, našel jsem chybu kde Caroline posílá dopis do tvé schránky a "znění je Posílám ti zeleninu, kterou pěstuji na mé malé zahrádce za domem atd... ale v dopise žádná zelenina není, zkoušel jsem to bez češtiny a tam je... jsem v druhém roce podzim 17den. Další maličkost je kde George říká větu "Ales je můj vnuk. Už jsem ti to říkal? Má tam být "Alex", díky

**Comment by Tsbook** [comment]
Opraveno v nejnovější verzi překladu.
